### ISSUE TITLE
how to write with input type="file"

### ISSUE THREAD

**Issue by maungyehtunzaw** [codekraft-studio/angular-image-preview#2]
<input type='file' media-preview class="media-preview"></media-preview>

**Comment by codekraft-studio** [comment]
can you be more precise please?

This will automatically create the input element:
```html
<media-preview model="myModel"></media-preview>
```

I guess right now is not possible. I need to think about it.

**Comment by b4dnewz** [comment]
now the [readme](https://github.com/codekraft-studio/angular-media-preview/blob/master/README.md) is updated with the documentation to how to use it as an attribute in input type file elements.
